apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    name: in-cluster
  project: default
  sources:
    # Chart from Chart Repo
    - chart: hello-world
      # repoURL: oci://docker.io/yyosefi
      repoURL: https://helm.github.io/examples
      targetRevision: 0.1.0
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        - $values/multiple-source-application/values-stage.yaml
    # Values from Git
    - repoURL: 'https://github.com/yyosefi/argo-cd-helm-values-demo'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true