apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    name: 'in-cluster'
  project: default
  source:
    chart: hello-world
    repoURL: oci://docker.io/yyosefi
    targetRevision: 0.1.0
    helm:
      values: |
        replicaCount: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true