apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    name: in-cluster
  project: default
  source:
    chart: hello-world
    repoURL: oci://ghcr.io/yyosefi
    targetRevision: 0.1.0
    helm:
      values: |
        replicaCount: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true